# Generated by Django 2.0.2 on 2018-02-07 20:15

import django.core.validators
from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('house', models.CharField(choices=[('GR', 'Gryffindor'), ('SL', 'Slytherin'), ('RA', 'Ravenclaw'), ('HU', 'Hufflepuff')], default='HU', max_length=2)),
                ('year', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['house', 'last_name', 'first_name'],
            },
        ),
    ]
