# Generated by Django 2.0.2 on 2018-02-12 20:31

import django.core.validators
from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dad_house', models.CharField(choices=[('GR', 'Gryffindor'), ('SL', 'Slytherin'), ('RA', 'Ravenclaw'), ('HU', 'Hufflepuff'), ('NO', 'None')], default='NO', max_length=2)),
                ('mom_house', models.CharField(choices=[('GR', 'Gryffindor'), ('SL', 'Slytherin'), ('RA', 'Ravenclaw'), ('HU', 'Hufflepuff'), ('NO', 'None')], default='NO', max_length=2)),
                ('birth_year', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2018), django.core.validators.MinValueValidator(1900)])),
            ],
            options={
                'ordering': ['birth_year', 'last_name', 'first_name', 'dad_house', 'mom_house'],
            },
        ),
    ]
