# Generated by Django 2.0.2 on 2018-02-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_baby'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Baby',
            new_name='MagicalBaby',
        ),
    ]
