# Generated by Django 2.0.2 on 2018-02-12 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20180212_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicalbaby',
            name='birth_year',
            field=models.IntegerField(default=1997, validators=[django.core.validators.MaxValueValidator(2018), django.core.validators.MinValueValidator(1900)]),
        ),
    ]
